### ISSUE TITLE
[REQUEST] Add "LIVE" indication

### ISSUE THREAD

**Issue by Benjozork** [ZigTag/fbw-map#10]
For: flybywiresim/website

Requirements:

- "LIVE" indication on the top left of the map
- Blinking (with fade) circle
- Drop shadow
- Disabled by default (enabled via prop)

![image](https://user-images.githubusercontent.com/4503241/105913903-894eb980-5ffb-11eb-91cb-c3e003d2eec7.png)

**Comment by nistei** [comment]
Top-left has the search bar currently. Will be tricky. WIll put it in the top-right corner.

**Comment by nistei** [comment]
Deprecated repo
